model:
  name: dae
  vector_length: 64
  bottle_neck: False
data:
  type: npz
  array_name: arr_0.npy
  dataset: norm_mask_64
  dim: 32
  path: D:/CV/3d_pca/voxels.npz
training:
  train_iters: 500000
  batch_size: 32
  n_workers: 1
  print_interval: 50
  save_interval: 10000
  optimizer:
    name: 'sgd'
    lr: 0.01
    weight_decay: 0.0005
    momentum: 0.99
  augmentations:
    noise: 0.05
  loss:
    name: dae
  lr_schedule:
    name: poly_lr
    max_iter: 200000
  resume:
testing:
  model_path: runs/dae/59761/dae_norm_mask_64_30000_model.pkl
  test_dataset: norm_mask_64
  vis: True
  save_recon: True
  save_path: dae_res
  batch_size: 1
  n_workers: 1
