model:
  name: dae
  vector_length: 128
  bottle_neck: False
data:
  type: npz
  array_name: arr_0.npy
  dataset: shapenet_all
  dim: 32
  path: voxels.npz
training:
  train_iters: 500000
  batch_size: 64
  n_workers: 1
  print_interval: 50
  save_interval: 1000
  optimizer:
    name: 'sgd'
    lr: 0.01
    weight_decay: 0.0005
    momentum: 0.99
  augmentations:
    noise: 0.05
  loss:
    name: dae
  lr_schedule:
    name: poly_lr
    max_iter: 200000
  resume:
testing:
  model_path: runs/dae/25597/dae_shapenet_all_211000_model.pkl
  test_dataset: shapenet_all
  vis: True
  save_recon: True
  save_path: dae_res
  batch_size: 1
  n_workers: 1
