model:
  name: vae
  vector_length: 20
data:
  dataset: coco_norm_64
  train_file: train.txt
  img_h: 64
  img_w: 64
  path: /ssd2/wenqiang/ae/data
training:
  train_iters: 500000
  batch_size: 128
  n_workers: 16
  print_interval: 50
  save_interval: 10000
  optimizer:
    name: 'sgd'
    lr: 0.01
    weight_decay: 0.0005
    momentum: 0.99
  augmentations:
    noise: 0.05
  loss:
    name: vae
  lr_schedule:
    name: poly_lr
    max_iter: 200000
  resume:
